/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admindesk;

/**
 *
 * @author jhann
 */
public class AddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EmployeeDetails = new javax.swing.JLabel();
        Position = new javax.swing.JLabel();
        InputEmployeeID = new javax.swing.JTextField();
        InputPos = new javax.swing.JTextField();
        EmployeeID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        InputName = new javax.swing.JTextField();
        Department = new javax.swing.JLabel();
        InputDept = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        InputEmail = new javax.swing.JTextField();
        Pnumber = new javax.swing.JLabel();
        InputPnumber = new javax.swing.JTextField();
        btnADD = new javax.swing.JButton();
        btnCANCEL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeDetails.setBackground(new java.awt.Color(204, 204, 204));
        EmployeeDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmployeeDetails.setText("EMPLOYEE DETAILS");
        jPanel1.add(EmployeeDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        Position.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Position.setText("Position :");
        jPanel1.add(Position, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 226, -1, 30));

        InputEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEmployeeIDActionPerformed(evt);
            }
        });
        jPanel1.add(InputEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 185, -1));

        InputPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPosActionPerformed(evt);
            }
        });
        jPanel1.add(InputPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 185, -1));

        EmployeeID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmployeeID.setText("Employee ID :");
        jPanel1.add(EmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 40));

        Name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Name.setText("Name :");
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 146, 90, 30));

        InputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNameActionPerformed(evt);
            }
        });
        jPanel1.add(InputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 185, -1));

        Department.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Department.setText("Department :");
        jPanel1.add(Department, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, 20));

        InputDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDeptActionPerformed(evt);
            }
        });
        jPanel1.add(InputDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 185, -1));

        Email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Email.setText("Email :");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 37, 40));

        InputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEmailActionPerformed(evt);
            }
        });
        jPanel1.add(InputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 185, -1));

        Pnumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Pnumber.setText("Phone Number :");
        jPanel1.add(Pnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, 20));

        InputPnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPnumberActionPerformed(evt);
            }
        });
        jPanel1.add(InputPnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 185, -1));

        btnADD.setBackground(new java.awt.Color(255, 102, 102));
        btnADD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });
        jPanel1.add(btnADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        btnCANCEL.setBackground(new java.awt.Color(255, 102, 102));
        btnCANCEL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCANCEL.setText("CANCEL");
        btnCANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCANCELActionPerformed(evt);
            }
        });
        jPanel1.add(btnCANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        Employees AddFrame = new Employees();
            AddFrame.setVisible(true);
            AddFrame.pack();
        AddFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnADDActionPerformed

    private void btnCANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCANCELActionPerformed
        Employees CancelFrame = new Employees();
            CancelFrame.setVisible(true);
            CancelFrame.pack();
        CancelFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCANCELActionPerformed

    private void InputPnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPnumberActionPerformed

    private void InputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEmailActionPerformed

    private void InputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNameActionPerformed

    private void InputEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEmployeeIDActionPerformed

    private void InputPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPosActionPerformed

    private void InputDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDeptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Department;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel EmployeeDetails;
    private javax.swing.JLabel EmployeeID;
    private javax.swing.JTextField InputDept;
    private javax.swing.JTextField InputEmail;
    private javax.swing.JTextField InputEmployeeID;
    private javax.swing.JTextField InputName;
    private javax.swing.JTextField InputPnumber;
    private javax.swing.JTextField InputPos;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Pnumber;
    private javax.swing.JLabel Position;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnCANCEL;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
