/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admindesk;

/**
 *
 * @author jhann
 */
public class EditEmployee extends javax.swing.JFrame {


    /**
     * Creates new form ViewEmployee
     */
    public EditEmployee() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editEmpInfo = new javax.swing.JLabel();
        EID = new javax.swing.JLabel();
        EmpID = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        EditName = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        EditEmail = new javax.swing.JTextField();
        Position = new javax.swing.JLabel();
        EditPos = new javax.swing.JTextField();
        Department = new javax.swing.JLabel();
        EditDept = new javax.swing.JTextField();
        btnSAVE = new javax.swing.JButton();
        btnCANCEL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        editEmpInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editEmpInfo.setText("Edit Employee's Information");

        EID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EID.setText("Employee ID :");

        EmpID.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        EmpID.setText("(di dapat naeedit)");
        EmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIDActionPerformed(evt);
            }
        });

        Name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Name.setText("Name :");

        EditName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditNameActionPerformed(evt);
            }
        });

        Email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Email.setText("Email :");

        EditEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEmailActionPerformed(evt);
            }
        });

        Position.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Position.setText("Position :");

        EditPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPosActionPerformed(evt);
            }
        });

        Department.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Department.setText("Department :");

        EditDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDeptActionPerformed(evt);
            }
        });

        btnSAVE.setBackground(new java.awt.Color(255, 102, 102));
        btnSAVE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSAVE.setText("Save");
        btnSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAVEActionPerformed(evt);
            }
        });

        btnCANCEL.setBackground(new java.awt.Color(255, 102, 102));
        btnCANCEL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCANCEL.setText("Cancel");
        btnCANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCANCELActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Department, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(editEmpInfo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(btnSAVE)
                        .addGap(54, 54, 54)
                        .addComponent(btnCANCEL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EID)
                            .addComponent(Position))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmpID, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(EditName)
                            .addComponent(EditEmail)
                            .addComponent(EditPos)
                            .addComponent(EditDept))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(editEmpInfo)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EID)
                    .addComponent(EmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(EditName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(EditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Position)
                    .addComponent(EditPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Department)
                    .addComponent(EditDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSAVE)
                    .addComponent(btnCANCEL)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EmpIDActionPerformed

    private void EditNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditNameActionPerformed

    private void EditEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditEmailActionPerformed

    private void EditPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditPosActionPerformed

    private void EditDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditDeptActionPerformed

    private void btnSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAVEActionPerformed
        // TODO add your handling code here:
        Employees SaveFrame = new Employees();
            SaveFrame.setVisible(true);
            SaveFrame.pack();
        SaveFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSAVEActionPerformed

    private void btnCANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCANCELActionPerformed
        // TODO add your handling code here:
        Employees CancelFrame = new Employees();
            CancelFrame.setVisible(true);
            CancelFrame.pack();
        CancelFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCANCELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Department;
    private javax.swing.JLabel EID;
    private javax.swing.JTextField EditDept;
    private javax.swing.JTextField EditEmail;
    private javax.swing.JTextField EditName;
    private javax.swing.JTextField EditPos;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmpID;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Position;
    private javax.swing.JButton btnCANCEL;
    private javax.swing.JButton btnSAVE;
    private javax.swing.JLabel editEmpInfo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
