
package admindesk;


public class Employees extends javax.swing.JFrame {
    
    /**
     * Creates new form User_Login
     */
    public Employees() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANEL = new javax.swing.JPanel();
        EMPLOYEE = new javax.swing.JLabel();
        ADD = new javax.swing.JButton();
        REMOVE = new javax.swing.JButton();
        EDIT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE = new javax.swing.JTable();
        ELIST = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PANEL.setBackground(new java.awt.Color(255, 153, 153));

        EMPLOYEE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EMPLOYEE.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        EMPLOYEE.setText("EMPLOYEE MANAGEMENT");

        ADD.setBackground(new java.awt.Color(255, 102, 102));
        ADD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ADD.setText("ADD EMPLOYEE");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        ADD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ADDKeyReleased(evt);
            }
        });

        REMOVE.setBackground(new java.awt.Color(255, 102, 102));
        REMOVE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        REMOVE.setText("REMOVE EMPLOYEE");
        REMOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMOVEActionPerformed(evt);
            }
        });

        EDIT.setBackground(new java.awt.Color(255, 102, 102));
        EDIT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EDIT.setText("EDIT EMPLOYEE");
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });

        TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "EMPLOYEE ID", "NAME", "EMAIL", "POSITION", "DEPARTMENT"
            }
        ));
        jScrollPane1.setViewportView(TABLE);

        ELIST.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ELIST.setText("Employee List :");

        javax.swing.GroupLayout PANELLayout = new javax.swing.GroupLayout(PANEL);
        PANEL.setLayout(PANELLayout);
        PANELLayout.setHorizontalGroup(
            PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANELLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PANELLayout.createSequentialGroup()
                        .addComponent(ADD)
                        .addGap(73, 73, 73)
                        .addComponent(EDIT)
                        .addGap(78, 78, 78)
                        .addComponent(REMOVE))
                    .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ELIST)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119))
            .addGroup(PANELLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(EMPLOYEE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PANELLayout.setVerticalGroup(
            PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(EMPLOYEE)
                .addGap(29, 29, 29)
                .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(REMOVE)
                    .addComponent(EDIT)
                    .addComponent(ADD))
                .addGap(39, 39, 39)
                .addComponent(ELIST)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        getContentPane().add(PANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        AddEmployee adem = new AddEmployee();
        adem.setVisible(true);
        adem.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ADDActionPerformed

    private void REMOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVEActionPerformed
        RemoveEmployee remve = new RemoveEmployee();
        remve.setVisible(true);
        remve.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_REMOVEActionPerformed

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
        EditEmployee edit = new EditEmployee();
        edit.setVisible(true);
        edit.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_EDITActionPerformed

    private void ADDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ADDKeyReleased
        
    }//GEN-LAST:event_ADDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees().setVisible(true);
                new Employees().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton EDIT;
    private javax.swing.JLabel ELIST;
    private javax.swing.JLabel EMPLOYEE;
    private javax.swing.JPanel PANEL;
    private javax.swing.JButton REMOVE;
    private javax.swing.JTable TABLE;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
